application: periscope
version: 3
runtime: python27
api_version: 1
threadsafe: true

env_variables:
    name: 'Periscope'

handlers:
- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /images
  static_dir: static/images

- url: /.*
  script: periscope.app

libraries:
- name: jinja2
  version: latest
